### ISSUE TITLE
SVW What's On Page - Details

### ISSUE THREAD

**Issue by mollywhyte** [katbow/worthwhile-hackathon#1]
Here is the message from Rachel with details about the SVW What's On page project:

OK so change of plan - slightly different project because the code for the awards stuff is all on the old system and very difficult to access/share

New project: Our What's On page has developed over the last few years but I'd love it to be more interactive and useful for (1) student volunteers looking for events, and (2) impact measurement. This could mean adding a map, adding filtering to the page, or creating a page with total number of events, projected attendees, number of events per region in the UK etc. are displayed to give more of a big picture overview of what's going on during the week.

You'll need:
1. Here's how the page displays https://www.studentvolunteeringweek.org/whats-on
2. Here's where people add events https://events.studentvolunteeringweek.org/add
Feel free to make an account to test it out, or use the Oxford Hub one
3.  Jon's going to Slack you some bits of code for the form and the viewing page

Here's the code from Jon: 

[svw whats on code.zip](https://github.com/katbow/worthwhile-hackathon/files/240393/svw.whats.on.code.zip)

**Comment by samhstn** [comment]
Thanks for the info @mollywhyte moving the information to the wiki
